SLEEP_INTERVAL_BETWEEN_MEASUREMENTS_TRANSMISSION_SECONDS = 5
WDT_MAX_INTERVAL_IN_SECONDS = 10_000 + SLEEP_INTERVAL_BETWEEN_MEASUREMENTS_TRANSMISSION_SECONDS * 1000
SLEEP_INTERVAL_ON_ERROR_IN_MAIN_LOOP = 5
MAX_WDT_INTERVAL_FOR_RP2040 = 8388

SLEEP_INTERVAL_ON_ERROR_SECS = 5 * 60
SLEEP_INTERVAL_BETWEEN_MEASUREMENTS_SECS = 5 * 60
